const fs = require('fs');

const lines = [
'"use client";',
'',
'import { useState } from "react";',
'import { categories, Category } from "@/lib/events";',
'import EventCard from "@/components/EventCard";',
'import CategoryFilter from "@/components/CategoryFilter";',
'import RecommendedEvents from "@/components/RecommendedEvents";',
'',
'interface Event {',
'  id: string;',
'  title: string;',
'  location: string;',
'  venue: string;',
'  category: string;',
'  date: string;',
'  time: string;',
'  description: string;',
'  highlights: string[];',
'  speaker?: string;',
'  speaker_title?: string;',
'  price: string;',
'  image_color: string;',
'  tag?: string;',
'  featured?: boolean;',
'}',
'',
'export default function HomeClient({ events }: { events: Event[] }) {',
'  const [activeCategory, setActiveCategory] = useState<Category | "All">("All");',
'  const [search, setSearch] = useState("");',
'',
'  const waLink = "https://wa.me/2349044209650?text=Hi, I want to feature my event on VENEW";',
'',
'  const filtered = events.filter((e) => {',
'    const matchesCategory = activeCategory === "All" || e.category === activeCategory;',
'    const matchesSearch =',
'      search === "" ||',
'      e.title.toLowerCase().includes(search.toLowerCase()) ||',
'      e.location.toLowerCase().includes(search.toLowerCase()) ||',
'      e.description?.toLowerCase().includes(search.toLowerCase());',
'    return matchesCategory && matchesSearch;',
'  });',
'',
'  const featuredEvents = filtered.filter((e) => e.featured);',
'  const regularEvents = filtered.filter((e) => !e.featured);',
'',
'  return (',
'    <div style={{ backgroundColor: "#FFFFFF", minHeight: "100vh" }}>',
'      <section style={{',
'        padding: "80px 24px 60px",',
'        background: "linear-gradient(135deg, #FFFBF0 0%, #FFFFFF 60%)",',
'        borderBottom: "1px solid #F0F0F0",',
'      }}>',
'        <div style={{ maxWidth: "1100px", margin: "0 auto" }}>',
'          <p style={{ color: "#D97706", fontSize: "11px", fontWeight: 600, letterSpacing: "0.3em", textTransform: "uppercase", marginBottom: "16px" }}>',
'            Events & Opportunities',
'          </p>',
'          <h1 style={{ fontFamily: "Georgia, serif", fontSize: "clamp(40px, 8vw, 80px)", fontWeight: 900, color: "#111827", lineHeight: 1, marginBottom: "24px" }}>',
"            Discover What's",
'            <br />',
'            <span style={{ color: "#F5A623" }}>Happening & Possible.</span>',
'          </h1>',
'          <p style={{ color: "#6B7280", fontSize: "18px", lineHeight: 1.7, maxWidth: "520px", marginBottom: "8px" }}>',
'            Explore events, opportunities, communities, workshops, conferences, and experiences designed to help you grow.',
'          </p>',
'          <p style={{ color: "#9CA3AF", fontSize: "15px", lineHeight: 1.7, maxWidth: "480px", marginBottom: "40px" }}>',
'            Find your next event, opportunity, or meaningful connection.',
'          </p>',
'          <div style={{ display: "flex", gap: "48px", marginBottom: "32px", flexWrap: "wrap" }}>',
'            {[',
'              { label: "Listings", value: String(events.length) },',
'              { label: "Cities", value: "3" },',
'              { label: "Categories", value: String(categories.length) },',
'            ].map(({ label, value }) => (',
'              <div key={label}>',
'                <p style={{ fontFamily: "Georgia, serif", fontSize: "36px", fontWeight: 900, color: "#F5A623", lineHeight: 1 }}>{value}</p>',
'                <p style={{ color: "#9CA3AF", fontSize: "11px", textTransform: "uppercase", letterSpacing: "0.2em", marginTop: "6px" }}>{label}</p>',
'              </div>',
'            ))}',
'          </div>',
'          <div style={{ display: "inline-flex", alignItems: "center", gap: "12px", backgroundColor: "#FFF8E7", border: "1px solid #F5A623", borderRadius: "12px", padding: "12px 20px", marginBottom: "32px", flexWrap: "wrap" }}>',
'            <span style={{ fontSize: "20px" }}>⭐</span>',
'            <p style={{ color: "#374151", fontSize: "14px" }}>Want your event featured at the top?</p>',
'            <a href={waLink} target="_blank" rel="noopener noreferrer" style={{ backgroundColor: "#F5A623", color: "#FFFFFF", fontWeight: 700, fontSize: "13px", padding: "8px 16px", borderRadius: "999px", textDecoration: "none", whiteSpace: "nowrap" }}>',
'              Feature My Event',
'            </a>',
'          </div>',
'          <div style={{ position: "relative", maxWidth: "600px" }}>',
'            <span style={{ position: "absolute", left: "18px", top: "50%", transform: "translateY(-50%)", fontSize: "18px", pointerEvents: "none" }}>🔍</span>',
'            <input',
'              type="text"',
'              placeholder="Search events, opportunities, cities, topics..."',
'              value={search}',
'              onChange={(e) => setSearch(e.target.value)}',
'              style={{ width: "100%", backgroundColor: "#FFFFFF", border: "1.5px solid #E5E7EB", borderRadius: "999px", padding: "16px 20px 16px 52px", color: "#111827", fontSize: "15px", outline: "none", boxSizing: "border-box", boxShadow: "0 2px 8px rgba(0,0,0,0.06)" }}',
'              onFocus={(e) => { e.target.style.borderColor = "#F5A623"; e.target.style.boxShadow = "0 0 0 3px rgba(245,166,35,0.12)"; }}',
'              onBlur={(e) => { e.target.style.borderColor = "#E5E7EB"; e.target.style.boxShadow = "0 2px 8px rgba(0,0,0,0.06)"; }}',
'            />',
'            {search && (',
'              <button onClick={() => setSearch("")} style={{ position: "absolute", right: "16px", top: "50%", transform: "translateY(-50%)", backgroundColor: "#F3F4F6", border: "none", borderRadius: "50%", width: "24px", height: "24px", color: "#6B7280", cursor: "pointer", fontSize: "12px", display: "flex", alignItems: "center", justifyContent: "center" }}>',
'                ✕',
'              </button>',
'            )}',
'          </div>',
'        </div>',
'      </section>',
'',
'      <div style={{ height: "1px", backgroundColor: "#F0F0F0", margin: "0 24px" }} />',
'',
'      <div style={{ paddingTop: "48px", backgroundColor: "#FFFFFF" }}>',
'        <RecommendedEvents events={events} />',
'      </div>',
'',
'      <section style={{ padding: "48px 24px 80px", backgroundColor: "#FFFFFF" }}>',
'        <div style={{ maxWidth: "1100px", margin: "0 auto" }}>',
'          <div style={{ display: "flex", flexWrap: "wrap", alignItems: "flex-start", justifyContent: "space-between", gap: "20px", marginBottom: "36px" }}>',
'            <div>',
'              <h2 style={{ fontFamily: "Georgia, serif", fontSize: "28px", fontWeight: 700, color: "#111827" }}>',
'                {search ? `Results for "${search}"` : "Browse Events & Opportunities"}',
'              </h2>',
'              <p style={{ color: "#9CA3AF", fontSize: "14px", marginTop: "4px" }}>',
'                {filtered.length} listing{filtered.length !== 1 ? "s" : ""} found',
'              </p>',
'            </div>',
'            <CategoryFilter active={activeCategory} onChange={setActiveCategory} />',
'          </div>',
'',
'          {featuredEvents.length > 0 && (',
'            <div style={{ marginBottom: "40px" }}>',
'              <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "20px" }}>',
'                <span style={{ fontSize: "18px" }}>⭐</span>',
'                <h3 style={{ fontFamily: "Georgia, serif", fontSize: "20px", fontWeight: 700, color: "#D97706" }}>Featured Events & Opportunities</h3>',
'              </div>',
'              <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))", gap: "24px" }}>',
'                {featuredEvents.map((event, i) => (',
'                  <EventCard key={event.id} event={event as any} index={i} />',
'                ))}',
'              </div>',
'              <div style={{ height: "1px", backgroundColor: "#F0F0F0", margin: "40px 0" }} />',
'            </div>',
'          )}',
'',
'          {regularEvents.length > 0 ? (',
'            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))", gap: "24px" }}>',
'              {regularEvents.map((event, i) => (',
'                <EventCard key={event.id} event={event as any} index={i} />',
'              ))}',
'            </div>',
'          ) : filtered.length === 0 ? (',
'            <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "96px 0", textAlign: "center" }}>',
'              <p style={{ fontSize: "48px", marginBottom: "16px" }}>🔍</p>',
'              <p style={{ fontFamily: "Georgia, serif", fontSize: "20px", fontWeight: 700, color: "#111827", marginBottom: "8px" }}>No listings found</p>',
'              <p style={{ color: "#9CA3AF", fontSize: "14px", marginBottom: "24px" }}>Try a different search or category</p>',
'              <button onClick={() => { setSearch(""); setActiveCategory("All"); }} style={{ backgroundColor: "#F5A623", color: "#FFFFFF", fontWeight: 700, fontSize: "14px", padding: "12px 24px", borderRadius: "999px", border: "none", cursor: "pointer" }}>',
'                Clear filters',
'              </button>',
'            </div>',
'          ) : null}',
'        </div>',
'      </section>',
'    </div>',
'  );',
'}',
];

require('fs').writeFileSync('components/HomeClient.tsx', lines.join('\n'));
console.log('Done! HomeClient.tsx fixed successfully.');